grafana:
  # 1. IL TUO FIX PER LA RETE (Bypassa il blocco di Minikube)
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 10.96.0.10
      - 8.8.8.8
    searches:
      - monitoring.svc.cluster.local # Aggiornato al namespace corretto
      - svc.cluster.local
      - cluster.local
    options:
      - name: ndots
        value: "2"

  # 2. IL DOWNLOAD DEL PLUGIN (Ora funzionerà perché Grafana userà 8.8.8.8 per risolvere grafana.com)
  plugins:
    - yesoreyeram-infinity-datasource

  # 3. I TUOI DATA SOURCES
  additionalDataSources:
    - name: loki
      type: loki
      access: proxy
      url: http://loki:3100
      jsonData:
        httpHeaderName1: 'X-Scope-OrgID'
      secureJsonData:
        httpHeaderValue1: 'local'
        
    - name: Infinity-API
      type: yesoreyeram-infinity-datasource
      access: proxy
      isDefault: false
      jsonData:
        allowedHosts:
          - http://host.minikube.internal:8000