services:
  # 1. Il Server MCP
  mcp_server:
    build: ./MCPContainer
    container_name: mcp_server
    networks:
      - agentic_net
    ports:
      - "8080:8080"

  # 2. La Gerarchia Agenti
  agentic_system:
    build: ./agentContainer
    container_name: agentic_system
    networks:
      - agentic_net
    environment:
      - MODEL_NAME=${MODEL_NAME}
      - PROVIDER=${PROVIDER}
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_SDK=${LLM_SDK}
    ports:
      - "8000:8000"
    depends_on:
      - mcp_server
    volumes:
      - ./agentLogs:/app/logs

  # 3. Il Motore SUMO
  sumo_simulation:
    build: ./simulationContainer
    container_name: sumo_simulation
    networks:
      - agentic_net
    environment:
      - DISPLAY=${DISPLAY}
      - LIBGL_ALWAYS_SOFTWARE=1
      - AGENT_URL=http://agentic_system:8000/trigger_step
      - SUMO_HOME=/usr/share/sumo
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    depends_on:
      - mcp_server
      - agentic_system

networks:
  agentic_net:
    driver: bridge