"""
È l'architetto logico dell'orchestratore globale.
Riceve gli output degli agenti locali, li comprime in un contesto testuale
e invia tutto all'LLM per ottenere una direttiva globale.
"""

import json
import os
from datetime import datetime
from fastmcp import Client

from llm_connector import AgentConnector
from orchestrator.orchestrator_policies import PROMPT_MCP

LOG_DIR = "/app/logs"
os.makedirs(LOG_DIR, exist_ok=True)

# Parametri per evitare looping e hallucination
MAX_ITERATIONS = 7
REQUIRED_TOOLS = {"save_agent_stress", "get_recent_stress"}

class Orchestrator:

    def __init__(self, mcp_url="http://mcp_server:8080", model_name="gemini-2.5-pro", provider="cloud"):
        self.id = "global_orchestrator"
        self.connector = AgentConnector(agent_name=self.id,provider=provider,model_name=model_name)
        self.mcp_url = mcp_url
        self.openai_tools = self._define_tools()
        # Client MCP inizializzato in __aenter__, None finché l'agente non è attivo
        self._mcp_client: Client | None = None
    
    # --- Gestione ciclo di vita del client MCP ---

    async def __aenter__(self):
        """Apre la connessione SSE una sola volta. Chiamato automaticamente da 'async with'."""
        endpoint = f"{self.mcp_url}/sse"
        print(f"🔌 [{self.id}] Apertura connessione SSE persistente verso {endpoint}...")
        self._mcp_client = Client(endpoint)
        await self._mcp_client.__aenter__()
        print(f"✅ [{self.id}] Connessione SSE aperta con successo.")
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        """Chiude la connessione SSE. Chiamato automaticamente da 'async with' anche in caso di eccezione."""
        if self._mcp_client:
            print(f"🔌 [{self.id}] Chiusura connessione SSE persistente...")
            await self._mcp_client.__aexit__(exc_type, exc_val, exc_tb)
            self._mcp_client = None

    # --- Definizione tools MCP ---

    def _define_tools(self):
        """Definisce il JSON Schema dei tool per l'LLM."""
        openai_tools = [
            {
                "type": "function",
                "function": {
                    "name": "save_agent_stress",
                    "description": "Saves the stress state produced by a SINGLE agent into the backend",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "agent_id": {
                                "type": "string",
                                "description": "The unique identifier of the agent."
                            },
                            "stress_index": {
                                "type": "number",
                                "description": "The stress index calculated by the agent (float value)."
                            },
                            "prompt_text": {
                                "type": "string",
                                "description": "The textual reasoning or summary generated by the agent."
                            }
                        },
                        "required": ["agent_id", "stress_index", "prompt_text"]
                    }
                }
            },
            {
                "type": "function",
                "function": {
                    "name": "get_recent_stress",
                    "description": "Recover the most recently saved stress states from memory.",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "limit": {
                                "type": "integer",
                                "description": "The number of recent records to return."
                            }
                        },
                        "required": ["limit"] 
                    }
                }
            }
        ]
        return openai_tools
    
    # --- Definizione funzioni di utilità orchestratore ---

    def _log_interaction(self, step, prompt, response):
        filename = f"{LOG_DIR}/{self.id}.log"

        with open(filename, "a", encoding="utf-8") as f:

            f.write("\n" + "=" * 80 + "\n")
            f.write(f"START LOGGING STEP: {step} | TIME: {datetime.now()}\n")
            f.write("=" * 80 + "\n")
   
            f.write("PROMPT TO LLM :\n\n")
            f.write(prompt)
            f.write("\n"+ "-" * 80 + "\n")

            f.write("RESPONSE RECEIVED:\n\n")
            f.write(str(response) + "\n")

            f.write("\n" + "=" * 80 + "\n")
            f.write(f"FINISH LOGGING: {step}\n")
            f.write("=" * 80 + "\n")

    def _format_agents_to_text(self, agent_outputs):
        lines = ["Local Agent Output"]

        for out in agent_outputs:
            agent_id = out.get("agent_id", "unknown")
            zone = out.get("zone", "unknown")
            stress_index = out.get("stress_index", 0)
            prompt_text = out.get("prompt_text", "")
            actions = out.get("actions_taken", [])

            lines.append(
                f"- Agent:{agent_id} | Zone:{zone} | "
                f"StressIndex:{stress_index} | "
                f"ExecutedActions:{len(actions)}"
            )

            if prompt_text:
                lines.append(f"  Context:{prompt_text}")

            for action in actions:
                lines.append(
                    f"  -> Intersection:{action.get('intersection_id')} | "
                    f"Policy:{action.get('policy')} | "
                    f"Reason:{action.get('reasoning')}"
                )

        return "\n".join(lines)

    async def decide(self, step, agent_outputs, history_size):
        if not self._mcp_client:
            raise RuntimeError(f"[{self.id}] Client MCP non inizializzato.")

        print(f"\n🔮 [{self.id}] Inizio ciclo autonomo orchestratore per step {step}...")
        
        # Conversione delle informazioni ricevute dagli agent in formato testuale
        agent_outputs_text = self._format_agents_to_text(agent_outputs)
        # Recupero id agenti
        agent_ids = [out.get("agent_id", "unknown") for out in agent_outputs]
        
        self.prompt = PROMPT_MCP.format(history_size=history_size, agent_ids=agent_ids)

        """
        Creazione della chat ogni volta che viene invocato l'agent. Due motivi principali:
            1. Se creassimo una chat nell'init, ogni volta che inseriamo un nuovo messaggio, vengono caricati anche tutti i
               precedenti -> grande consumo di token
            2. L'agent non deve avere memoria -> è l'orchestratore la componente con memoria
        # """
        chat = self.connector.create_agentic_chat(
            system_instruction=self.prompt,
            openai_tools=self.openai_tools
        )

        # Invio del messaggio iniziale per innescare ragionamento orchestratore 
        initial_message = (
            "Agent reasoning finished\n"
            f"Current Step ID: {step}\n"
            f"{agent_outputs_text}\n"
        )

        response = await chat.send_message(initial_message)

        # Verifica dei tool da invocare
        if not response.function_calls:
            print(f"⚠️ [{self.id}] L'LLM ha ignorato i tool.")
            return {
                "global_reasoning": "Empty response",
                "directives": [
                    {
                        "target_agent": agent_id,
                        "action": "hold_or_balance",
                        "instruction": "No directive available"
                    }
                    for agent_id in agent_ids
                ]
            }

        # Loop agentico
        called_tools = set()
        iteration = 0
        last_stress = 0.0

        while response.function_calls and iteration < MAX_ITERATIONS:
            iteration += 1
            tool_responses = []

            for function_call in response.function_calls:
                func_name = function_call.name
                args = function_call.args
                call_id = function_call.id

                print(f"🤖 [{self.id}] Tool Calling: {func_name}")
                called_tools.add(func_name)

                try:
                    tool_result = await self._execute_mcp_call(func_name, args)
                except Exception as e:
                    print(f"❌ [{self.id}] Errore MCP Tool '{func_name}': {e}")
                    tool_result = {"error": str(e)}

                formatted_response = self.connector.format_tool_response(
                    func_name,
                    tool_result,
                    call_id
                )
                tool_responses.append(formatted_response)

            response = await chat.send_message(tool_responses)

        missing_tools = REQUIRED_TOOLS - called_tools
        if missing_tools:
            print(f"⚠️ [{self.id}] Tool obbligatori non chiamati: {missing_tools}")
            return {
                "global_reasoning": "Empty response",
                "directives": [
                    {
                        "target_agent": agent_id,
                        "action": "hold_or_balance",
                        "instruction": "No directive available"
                    }
                    for agent_id in agent_ids
                ]
            }

        raw_response = response.text
        #text = getattr(raw_response, "text", None) or getattr(raw_response, "content", "") or ""

        # Logging interazione orchestratore
        full_logged_prompt = (
            f"SYSTEM INSTRUCTION:\n{self.prompt}\n\n"
            f"EVENT TRIGGERED MESSAGE:\n{initial_message}"
        )
        self._log_interaction(step, full_logged_prompt, raw_response)

        # Parsing della risposta
        if not raw_response:
            return {
                "global_reasoning": "Empty response",
                "directives": [
                    {
                        "target_agent": agent_id,
                        "action": "hold_or_balance",
                        "instruction": "No directive available"
                    }
                    for agent_id in agent_ids
                ]
            }

        text = raw_response.strip().replace("```json", "").replace("```", "").strip()

        try:
            parsed = json.loads(text)
            return parsed
        except Exception:
            print(f"⚠️ [{self.id}] JSON non valido:\n{text}")
            return {
                "global_reasoning": "Invalid JSON",
                "directives": [
                    {
                        "target_agent": agent_id,
                        "action": "hold_or_balance",
                        "instruction": "Invalid orchestrator response"
                    }
                    for agent_id in agent_ids
                ]
            }
        
    async def _execute_mcp_call(self, tool_name: str, args: dict):
        """Esegue la chiamata MCP riutilizzando la connessione SSE persistente."""
        result = await self._mcp_client.call_tool(tool_name, args)
        return str(result)